### ISSUE TITLE
[SKALE-115] Implement key-value reduce extensions to EVM

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/skale-consensus#45]
<p>The reduce chain should perform key-value reduce operation similar to Hadoop/Spark</p><p><a href="https://www.safaribooksonline.com/library/view/learning-spark/9781449359034/ch04.html"
                class="external-link" rel="nofollow">https://www.safaribooksonline.com/library/view/learning-spark/9781449359034/ch04.html</a></p><p>Key-value reduce is needed to perform aggregation of payments or other
                operations performed in different Map chains in Map-Reduce atchitecture. Normally key is the payee and value is the amound paid</p><p>The result of map reduce performed for a particular reduce block shall be available as input to Map
                smart contracts for the next block</p><p>Example:</p><p>Each user maintains a payee account with a key on each Map subchain, and a payor account with the same key on a particular subchain. </p><p>Payee accounts are
                used to acumulate accepted payments, and payor accounts are used to pay.</p><p>After the Map phase a smart contract on each subchain produces a set of payee - amount key/value pairs that it wants to aggregated. The pairs are passed to the
                reduce phase and aggregated by key. This means that payments made to the same user on different subchains are aggregated. After that the aggregated payment message is send to the subchain where the corresponding user payor account is maintained, and
                the payor account is credited. </p><p>In this way payments can be scaled to millions of users.</p><p>To implement this we need key/value aggregation \(adding up values by key\) performed during the reduce phase and then
                <br/>message send operation that sends aggregated value to the subchain where the corresponding payor account is stored.</p>

**Comment by kladkogex** [comment]
Outdated
