### ISSUE TITLE
Change hash function in Oracle signing

### ISSUE THREAD

**Issue by payvint** [skalenetwork/skale-consensus#611]
Currently Oracle use SHA3-256 hashing algorithm to hash a message and then signing it, unfortunately we can not reproduce SHA3-256 hashing algorithm in Solidity. There are 2 hashes in Solidity: keccak256, sha256. If Oracle would use one of these algorithm - we would be able to verify a Oracle response in Solidity

### Suggested implementation:

Change SHA3-256 on KECCAK256

### Describe alternatives that you have considered:

Change SHA3-256 on SHA256

**Comment by gannakulikova** [comment]
Assigned for V2.1 release
