### ISSUE TITLE
[SKALE-459] Make C++ 17 available and chosen by default in skaled and mapreducing_consensus

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/skale-consensus#64]
<p>Update dependency libraries to newest versions not conflicting with C++17:</p><ul> <li><b>Crypto++</b> should be <b>7.0.0</b></li> <li><b>Boost</b> should be
                <b>1.69</b></li></ul><p>Set <b>CMAKE*CXX*STANDARD</b> variable should be set to <b>17</b> in the <b>skaled</b> and <b>mapreducing\_consensus</b> projects.</p>

**Comment by cstrangedk** [comment]
Completed 26DEC2018
