### ISSUE TITLE
[SKALE-758] Beacon (empty) block is missing

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/skale-consensus#67]
<p>Beacon block \(empty block\) should be created every 3 seconds if there are no transactions.</p><p>Expected result: <br/>empty block creation every 3 seconds given no transactions</p><p>Observed
                result:<br/>no blocks are created in the absence of transactions and<br/>peer is shut down after 4 minutes, <b>see last two timestamps</b></p><div class="code panel" style="border-width:
                1px;"><div class="codeContent panelContent"><pre class="code-java">\[2019-02-05 23:14:19.005\] \[0:main\] \[info\] COMPLETED CONSENSUS:BLOCK:1:PROPOSER:1\[2019-02-05 23:14:19.005\] \[0:main\] \[info\] Total transactions:0
                Time\(s\):267.692000\[2019-02-05 23:14:19.105\] \[0:main\] \[info\] PRPSR:1:BID: 1:HASH:a6cb453f:BLOCK*TXS:1:DMSG0:MPRPS:1:RPRPS:1:PTXNS:1:RTXNS:1:PNDG:1:KNWN:1:CMT:0:MGS:2:INSTS:2:BPS:1:TLS:0:HDRS:0\[2019-02-05 23:16:45.120\] \[0:main\] \[info\] Starting
                consensus <span class="code-keyword">for</span> block id:2\[2019-02-05 23:16:45.148\] \[0:main\] \[info\] COMPLETED CONSENSUS:BLOCK:2:PROPOSER:0\[2019-02-05 23:16:45.148\] \[0:main\] \[info\] Total transactions:1
                Time\(s\):413.835000\[2019-02-05 23:16:45.248\] \[0:main\] \[info\] PRPSR:0:BID: 2:HASH:0653be67:BLOCK*TXS:1:DMSG0:MPRPS:2:RPRPS:2:PTXNS:2:RTXNS:1:PNDG:1:KNWN:0:CMT:1:MGS:2:INSTS:4:BPS:2:TLS:0:HDRS:0\[2019-02-05 23:29:39.759\] \[0:main\] \[info\] Starting
                consensus <span class="code-keyword">for</span> block id:3\[2019-02-05 23:29:39.760\] \[0:main\] \[info\] COMPLETED CONSENSUS:BLOCK:3:PROPOSER:1\[2019-02-05 23:29:39.760\] \[0:main\] \[info\] Total transactions:2
                Time\(s\):1188.447000\[2019-02-05 23:29:39.860\] \[0:main\] \[info\] PRPSR:1:BID: 3:HASH:df2621bc:BLOCK*TXS:1:DMSG0:MPRPS:2:RPRPS:2:PTXNS:3:RTXNS:0:PNDG:1:KNWN:0:CMT:2:MGS:2:INSTS:6:BPS:2:TLS:0:HDRS:0\[2019-02-05 23:29:51.475\] \[0:main\] \[info\] Starting
                consensus <span class="code-keyword">for</span> block id:4\[2019-02-05 23:29:51.476\] \[0:main\] \[info\] COMPLETED CONSENSUS:BLOCK:4:PROPOSER:0\[2019-02-05 23:29:51.476\] \[0:main\] \[info\] Total transactions:3
                Time\(s\):1200.163000\[2019-02-05 23:29:51.576\] \[0:main\] \[info\] PRPSR:0:BID: 4:HASH:01861876:BLOCK*TXS:1:DMSG0:MPRPS:2:RPRPS:2:PTXNS:4:RTXNS:0:PNDG:1:KNWN:0:CMT:3:MGS:3:INSTS:8:BPS:2:TLS:0:HDRS:0\[2019-02-05 23:34:12.850\] \[0:main\] \[error\] :::The peer
                shut down the socket, bytes to read:8</pre></div></div>

**Comment by cstrangedk** [comment]
Completed 07FEB2019
