### ISSUE TITLE
Complete Oracle release and Oracle spec

### ISSUE THREAD

**Issue by kladkogex** [skalenetwork/skale-consensus#709]

**Comment by DmytroNazarenko** [comment]
Link to add information - https://github.com/skalenetwork/internal-support/blob/main/docs/issues-and-investigations/oracle-2.1release-spec.md

**Comment by oleksandrSydorenkoJ** [comment]
https://github.com/skalenetwork/skale-consensus/tree/beta/oracle#oracle-request-spec-description
1. Filed from eth_call methgods are required: from, to, data, gas - need to add to spec
2. Add ``cid, uint64 - chain ID`` - sid to skale chain, not mainnet
