### ISSUE TITLE
Catchup leaks memory

### ISSUE THREAD

**Issue by kladkogex** [skalenetwork/skale-consensus#714]
16 node test is not easy to run on a single machine, 4 node cluster is to small.

It is is good to have 7 node tests for things like memory consumption

**Comment by kladkogex** [comment]
After running tests today, i figured out why the memory was growing. It turns out you need to call LevelDB with a writeOptions sync parameter. Otherwise, things stay for a long time in RAM.

After the fix, consensus now does catchup drastically better, using less than 150M of RAM and not leaking memory.

**Comment by kladkogex** [comment]
We need to get it into 2.1 because it is a small configuration fix that greatly improves catchup

**Comment by DmytroNazarenko** [comment]
skaled:3.16.0-beta.6

**Comment by EvgeniyZZ** [comment]
Mark as resolved. Require more precise requirements
