### ISSUE TITLE
Node takes more than 10 minutes to start up after shut down for 2 days

### ISSUE THREAD

**Issue by OleksanderSalamatov** [skalenetwork/skale-consensus#734]
We encountered issue when skaled takes too long to start from catchup after 2 days of shutdown
Issue war reproduced during update skaled from 3.16.0-beta.10 (skaled crashes after startup) to 3.16.0-beta.11 (skaled works correctly after startup)
There was 7 schains on node at the moment of update to 3.16.0-beta.10 and update to 3.16.0-beta.11 and CPU load during skaled startup from catchup was nearly 100%
 
![image](https://user-images.githubusercontent.com/84843611/218508113-f172cda2-8bd9-4bc0-a5d8-0ff38491facb.png)

Preconditions:
 7 or more up and running skale chains on node A
Skaled version with detailed consensus log
Steps to reproduse:
1) Update nodes to skaled version with detailed consensus log
2) Stop node A (or all skaleds on it) for 2-3 days
3) After time has passed turn on node(skaled) and monitor logs on node A, logs on sending node and CPU load

Expected result: cpu load is not 100% and catchup takes around 2 minutes

Actual result: cpu load is 100% and catchup takes 10+ minutes

**Comment by kladkogex** [comment]
We have faster catchup now in 2.2
