### ISSUE TITLE
Incorrect exit in the middle of block execution

### ISSUE THREAD

**Issue by dimalit** [skalenetwork/skale-consensus#775]
Actual:

1. 4 nodes
2. exitGracefully() is called inside createBlock()
3. createBlock() doesn't return for 40 sec (for testing)
4. consensus outputs `No luck exiting on block boundary. Exiting immediately`

Expected:
consensus should not include time, when it was waiting for skaled, in it's own timeout - and in this case should not consider this exit as "not on block boundary"

**Comment by kladkogex** [comment]
Lets discuss exactly

**Comment by DmytroNazarenko** [comment]
Related to https://github.com/skalenetwork/skaled/issues/1425

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.1

**Comment by oleksandrSydorenkoJ** [comment]
Verified on 
skalenetwork/schain:3.17.0-beta.7-historic

Skaled wait for 270 seconds of the gracefully timeout after sigterm if consensus stuck during block processing 
 
[historic_block_call_during_proccessing_transactions.log](https://github.com/skalenetwork/skale-consensus/files/12371477/historic_block_call_during_proccessing_transactions.log)
