### ISSUE TITLE
Improve consensus throughput performance by 15%

### ISSUE THREAD

**Issue by kladkogex** [skalenetwork/skale-consensus#806]
### Describe the feature you would like:

Improve consensus throughput by 15%

Many small improvements to consensus to improve performance

**Comment by PolinaKiporenko** [comment]
3.19.0-beta.0

**Comment by oleksandrSydorenkoJ** [comment]
Consensus in the 2.4 release works 3.2 **times faster** than in 2.3.
2.3 - skale_schain_black-spherical-graffias (16 of 16)
2.4: skale_schain_carefree-knowing-sarin - (13 of 16 active nodes )

55 blocks: 
 
3.18.2
```
Total BLOCK_TXS : 15511
Average CWT: 2342.616666666667
Average SWT: 97.48333333333333
Average TLWT: 165.63333333333333
Average SBPT: 1194.7333333333333
Timeout between first and last timestamp: 0:02:28.038000
Average block mining time: 1.2419833333333332
```


3.19.0-beta.0
```
Total BLOCK_TXS : 1041
Average CWT: 732.2407407407408
Average SWT: 6.462962962962963
Average TLWT: 10.462962962962964
Average SBPT: 165.0
Timeout between first and last timestamp: 0:00:40.127000
Average block mining time: 0.38080555555555556
```

**Comment by oleksandrSydorenkoJ** [comment]
blocked by https://github.com/skalenetwork/skaled/issues/1919
