### ISSUE TITLE
eth_syncing info

### ISSUE THREAD

**Issue by olehnikolaiev** [skalenetwork/skale-consensus#813]
store `maxKnownBlock` on the node during catchup to implement `eth_syncing` on skaled side

relates to https://github.com/skalenetwork/skaled/issues/1199

**Comment by DmytroNazarenko** [comment]
skaled: 3.18.0-beta.0

**Comment by oleksandrSydorenkoJ** [comment]
Verified in a head issue 
https://github.com/skalenetwork/skaled/issues/1199#issuecomment-1914620667
